const LOGIN_ENDPOINT = '/api/public/login';
const USER_DATA_ENDPOINT = '/user';
const LEAVE_ENDPOINT = '/leave';
const PERMISSION_ENDPOINT = '/permissions';
const UPDATE_PERMISSION_ENDPOINT = '/permission';

export { LOGIN_ENDPOINT, USER_DATA_ENDPOINT, LEAVE_ENDPOINT, PERMISSION_ENDPOINT, UPDATE_PERMISSION_ENDPOINT };
