spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:devdb;DB_CLOSE_ON_EXIT=FALSE
    username: admin
    password: passw0rd
    driverClassName: org.h2.Driver

  jpa:
    open-in-view: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

  security:
    filter:
      order: 10

springdoc:
  swagger-ui:
    path: /swagger


server:
  port: 5000
  error:
    path: /error

jwt:
  secret: zdtlD3JK56m6wTTgsNFhqzjqP
  issuer: com.agh.iet
